### ISSUE TITLE
Examples with the same description should error

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#40]
If you have two diffux examples with the same description, there is currently a weird behavior where it will sometimes use the first one and sometimes use the second one. Instead, we should notice this and trigger an error.

```jsx
diffux.define('My component', function() { ... });
diffux.define('My component', function() { ... });
```

If we want to get really serious about these kinds of problems, we could write an ESLint plugin.

**Comment by lencioni** [comment]
Thinking about this a little more, I think my solution might not be good enough since we replace all special characters with `_` for the filename which makes these descriptions `<MyComponent>` and `>MyComponent<` essentially equivalent.

**Comment by trotzig** [comment]
I've been thinking of ways to fix the filename issue. It would be better if all characters were kept intact. But I don't want to keep all characters due to security issues and weird bugs because of bad filenames ending up being used. I've been looking for some kind of filename safe escaping implementation, but I haven't found anything yet.

It's one thing to strip out invalid characters. But what I want is a way to encode a string, decode it, and then have the original string back. Maybe a URL/URI encoder would do the trick? http://ruby-doc.org/stdlib-2.1.2/libdoc/uri/rdoc/URI/Escape.html. 

Another alternative could be to just base64 encode the string. But then the filesystem wouldn't make sense if you looked at directly. I'm not sure that's a great idea either.

**Comment by trotzig** [comment]
@lencioni: how would you feel if the folder name for an example used a base64 encoded version of the name? Instead of 

```
snapshots/_IconButton__with_border/baseline.png
snapshots/_IconButton__without_border/baseline.png
```

we would have

```
snapshots/PEljb25CdXR0b24+IHdpdGggYm9yZGVy/baseline.png
snapshots/PEljb25CdXR0b24+IHdpdGhvdXQgYm9yZGVy/baseline.png
```
?

This would fix the issue of two examples with similar description ending up in the same folder, e.g. `<foo>` and `@foo@` would both become `_foo_`.

**Comment by lencioni** [comment]
I think that's fine. If we want to make it easier to find the example you are looking for on the filesystem, we could emit a file that gives you a mapping to follow. Or put a file in each directory that contains the description.

**Comment by trotzig** [comment]
Okay, cool. I think I'll go ahead and make this change soon. Thanks for weighing in!

**Comment by trotzig** [comment]
I think that commit above closes this issue.
