### ISSUE TITLE
Remove React-specific code

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#47]
In our runner JS, we check if the element has `getDOMNode` on it and if it does, we call that to get the DOM node. This makes it a little easier to work with React, but the React API has changed to `React.findDOMNode` and more recently (0.14) to `ReactDOM.findDOMNode`.

We also have some code that uses `window.React` to unmount components.

In the long run we should probably make this tool React agnostic and push these requirements to the consumer. We will probably need some sort of `beforeEach` and `afterEach` to make this possible.

**Comment by trotzig** [comment]
I'm copy-pasting some discussion from a commit around the same issue:

@trotzig commented on 2d9b62e 5 days ago
I agree about the comment in the commit message about making it agnostic. beforeEach and afterEach sounds like a good plan. We should provide a way to access the DOM node, either through passing it in our some static way. The problem with passing it in is that it's inconsistent with how beforeEach works in Jasmine for instance (which is passing a done callback).

We could also allow you to define a diffux.tearDown(domElement) method that you can implement. That's actually a bit more straightforward. But then you wouldn't be able to use beforeEach/afterEach for other purposes.

@lencioni commented on 2d9b62e 5 days ago
A full implementation of beforeEach/afterEach would probably also require nestable diffux.define calls so that you can scope these functions to sets of examples.

@trotzig commented on 2d9b62e 4 days ago
True. I think we can stay lean by providing a way to tear down the DOM node to begin with. Being able to group examples and have before- and after-hooks would be a nice addition but at this time I think we can do without it.
